language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpulse-dev
  - sudo apt-get install -y libxrandr-dev

script:
  - make linux-debug64 && ./build/engine/linux64/bin/crown-debug-64 --run-unit-tests
  - make linux-development64 && ./build/engine/linux64/bin/crown-development-64 --run-unit-tests
  - make linux-release64
